#!/usr/bin/env python

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen.canvas import Canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import sys
import tempfile

from optparse import OptionParser
import os, subprocess

if len(sys.argv)<2:
    from PyQt4.QtGui import *
    from PyQt4.QtCore import *

def parse_range(astr):
    result=set()
    for part in astr.split(','):
        x=part.split('-')
        result.update(range(int(x[0]),int(x[-1])+1))
    return sorted(result)

def makelabels(stream, gen, labels, off):
    font=open("/tmp/3of9.ttf", "wb")
    font.write(fontdata.decode("base64"))
    font.close()
    pdfmetrics.registerFont(TTFont('3of9', '/tmp/3of9.ttf'))
    os.remove("/tmp/3of9.ttf")

    can=Canvas(stream, pagesize=letter)
    width, height=letter

    LABEL_WIDTH=3*72
    LABEL_HEIGHT=(5*72)/8
    CHAR_WIDTH=25
    CHAR_HEIGHT=13
    NUMBER_OFFSET=20
    BARCODE_OFFSET=30 #from right
    TOP_OFFSET=50
    LEFT_OFFSET=50
    HORIZ_SPACING=50
    VERT_SPACING=0
    MARGIN=2
    
    cols="red", "yellow", "lightgreen", "lightblue", "grey", "orange", "hotpink", "darkgreen", "darkorange", "purple"

    can.setFont("Helvetica", 10)
    can.setFillColor("black")
    can.drawString(125, height-15, "Print at 100% scale onto Avery labels 6577 using a good quality printer")
    can.setFillColor("blue")
    can.drawString(165, height-30, "Generated using PyLTO from MaNic Software")
    can.linkURL("http://www.manicsoftware.co.uk", (150, height-40, width-150, height-10))
    can.setFillColor("black")
    for i in range(len(labels)):
        n=i+off
        h=(n%2)*(LABEL_WIDTH+HORIZ_SPACING)+LEFT_OFFSET
        v=height-LABEL_HEIGHT-(n/2)*(LABEL_HEIGHT+VERT_SPACING)-TOP_OFFSET
        barcode="*{0:06d}L{1}*".format(int(labels[i]), gen)
        can.setFont("3of9", 42)
        can.scale(-1.0, 1.0)
        can.drawString(-(h+LABEL_WIDTH-BARCODE_OFFSET), v+MARGIN, barcode)
        can.scale(-1.0, 1.0)
        chars="{0:06d}".format(int(labels[i]))
        genchars="L"+str(gen)
        c=0
        can.setFont("Helvetica-Bold", 13)
        for char in chars:
            can.setFillColor(cols[int(char)])
            can.rect(h+c*CHAR_WIDTH+NUMBER_OFFSET, v+LABEL_HEIGHT-CHAR_HEIGHT-MARGIN, CHAR_WIDTH, CHAR_HEIGHT, fill=1)
            can.setFillColor("black")
            can.drawString(h+c*CHAR_WIDTH+7+NUMBER_OFFSET, v+2+LABEL_HEIGHT-CHAR_HEIGHT-MARGIN, char)
            c+=1
            
        can.setFont("Helvetica-Bold", 9)
        can.setFillColor("white")
        can.rect(h+c*CHAR_WIDTH+NUMBER_OFFSET, v+LABEL_HEIGHT-CHAR_HEIGHT-MARGIN, CHAR_WIDTH, CHAR_HEIGHT, fill=1)
        can.setFillColor("black")
        can.drawString(h+c*CHAR_WIDTH+6+NUMBER_OFFSET, v+3+LABEL_HEIGHT-CHAR_HEIGHT-MARGIN, genchars)
        
    can.showPage()
    can.save()

def gobutton():
    global gui
    global gen
    global numbers
    global offset

    off=offset.value()
    numlist=str(numbers.displayText()).split(" ")
    try:
        labels=parse_range(",".join(numlist))
    except:
        QMessageBox.critical(gui, 'PyLTO', "Number Range Invalid")
        return
    print labels
    if len(labels)>(32-off):
        QMessageBox.critical(gui, 'PyLTO', "Number Range Too Long (max 32)")
        return

    _,tmpfilename=tempfile.mkstemp(".pdf")
    file=open(tmpfilename, 'w')
    makelabels(file, int(gen.currentText()), labels, off)
    file.close()

    if sys.platform.startswith('darwin'):
        subprocess.call(('open', tmpfilename))
    elif os.name == 'nt':
        os.startfile(tmpfilename)
    elif os.name == 'posix':
        subprocess.call(('xdg-open', tmpfilename))

def main():

    if len(sys.argv)<2:
        global gui
        global gen
        global numbers
        global offset
        app = QApplication(sys.argv)
        gui = QWidget();
        gui.setWindowTitle("PyLTO")
        layout = QGridLayout(gui)
        genlabel = QLabel("Generation", gui)
        layout.addWidget(genlabel, 0, 0)
        gen = QComboBox(gui)
        for i in range(10):
            gen.addItem(str(i+1))
        gen.setCurrentIndex(3)
        layout.addWidget(gen, 0, 1)
        numlabel = QLabel("Numbers", gui)
        layout.addWidget(numlabel, 1, 0)
        numbers=QLineEdit(gui)
        layout.addWidget(numbers, 1, 1)
        offlabel = QLabel("Offset", gui)
        layout.addWidget(offlabel, 2, 0)
        offset = QSpinBox(gui)
        offset.setRange(0, 31)
        layout.addWidget(offset, 2, 1)
        button = QPushButton("Go", gui)
        button.clicked.connect(gobutton)
        layout.addWidget(button, 3, 0, 1, 2)
        gui.show()
        return app.exec_()
    else:
        parser=OptionParser(usage="%prog [options] numbers (e.g. 1-5,6,7,8 9-12)\nRun without options to launch UI (you'll need the pyqt4 libraries)")
        parser.add_option("-g", "--generation", dest="generation",
                          help="tape generation (defaults to 4)", type=int, default=4)
        parser.add_option("-o", "--offset", dest="offset",
                          help="skip the first 'offset' labels", type=int, default=0)
        (opts, args)=parser.parse_args()
        gen=int(opts.generation)
        off=int(opts.offset)
        
        if len(args)<1:
            sys.exit("Going to need some numbers here mate")
        labels=parse_range(",".join(args))
        if len(labels)>(32-off):
            sys.exit("Only 32 labels will fit on a page")
        
        makelabels(sys.stdout, gen, labels, off)


fontdata= \
"AAEAAAAKAIAAAwAgT1MvMnu0fOcAAACsAAAATmNtYXAB+wLuAAAA/AAAAXJnbHlmfm8KBAAAAnAA" + \
"AA22aGVhZBh23U8AABAoAAAANmhoZWEI4QNPAAAQYAAAACRobXR4AxAAAAAAEIQAAABgbG9jYUyK" + \
"T/gAABDkAAAAYG1heHAANQAWAAARRAAAACBuYW1lSHvdPQAAEWQAAAJxcG9zdAADAAAAABPYAAAA" + \
"JAAAAxABkAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAA" + \
"AABzZnQAAAAAIABfBgQAAAAABgQAAAAAAAAAAgABAAAAAAAUAAMAAQAAARoAAAAAAAAAAAAAAAAA" + \
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" + \
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" + \
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" + \
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" + \
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAWAAAAA4ACAACAAYAIAAlAC8AOQBaAF///wAAACAAJAAq" + \
"ADAAQQBf//8ACgAAAAD/1P/N/8sAAQAAAAwADgAAAAAAAAAAACsALgADAC0AAAAoACkALAAAAAEA" + \
"AAAAADQGAAADAAAzIxEzNDQ0BgD3AAEAAAAAAIwGAAADAAAzIxEzjIyMBgAAAAUAAAAAAtwGAAAD" + \
"AAcACwAPABMAADMjETMTIxEzASMRMwEjETMTIxEz9DQ0wIyM/oA0NAJAjIxoNDQGAPoABgD6AAYA" + \
"+gAGAPoABgAAAAUAAAAAAtwGAAADAAcACwAPABMAACEjETMBIxEzAyMRMwEjETMDIxEzAtw0NP3A" + \
"NDRoNDQCQIyMwIyMBgD6AAYA+gAGAPoABgD6AAYAAAUAAAAAAtwGAAADAAcACwAPABMAADMjETMB" + \
"IxEzASMRMwEjETMDIxEz9DQ0AeiMjP2wjIwBkDQ0aDQ0BgD6AAYA+gAGAPoABgD6AAYAAAUAAAAA" + \
"AtwGAAADAAcACwAPABMAACEjETMBIxEzEyMRMwEjETMDIxEzAbQ0NP6ANDTAjIwB6IyMwDQ0BgD6" + \
"AAYA+gAGAPoABgD6AAYAAAUAAAAAAtwGBAADAAcACwAPABMAACEjETMTIxEzASMRMwEjETMDIxEz" + \
"AUyMjMA0NP6AjIwCUDQ0aDQ0BgD6AAYA+gAGAPoEBgD5/AYAAAUAAAAAAtwGAAADAAcACwAPABMA" + \
"ACEjETMBIxEzAyMRMwEjETMBIxEzAhw0NP6ANDRoNDQCqIyM/tiMjAYA+gAGAPoABgD6AAYA+gAG" + \
"AAAABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMBIxEzASMRMwEjETMCDIyM/ug0NAGANDT+" + \
"GIyMAlA0NAYA+gAGAPoABgD6AAYA+gAGAAAFAAAAAALcBgAAAwAHAAsADwATAAAhIxEzASMRMxMj" + \
"ETMBIxEzEyMRMwJ0NDT9wDQ0wIyMARiMjNA0NAYA+gAGAPoABgD6AAYA+gAGAAAFAAAAAALcBgAA" + \
"AwAHAAsADwATAAAhIxEzAyMRMwMjETMBIxEzEyMRMwFcNDTANDRoNDQB6IyMwIyMBgD6AAYA+gAG" + \
"APoABgD6AAYAAAAFAAAAAALcBgAAAwAHAAsADwATAAAhIxEzAyMRMwEjETMBIxEzASMRMwJ0jIzA" + \
"NDT+2IyMAlA0NP4YNDQGAPoABgD6AAYA+gAGAPoABgACAAUAAAAAAtwGAAADAAcACwAPABMAACEj" + \
"ETMBIxEzEyMRMwEjETMTIxEzAbQ0NP6ANDTAjIwBgIyMaDQ0BgD6AAYA+gAGAPoABgD6AAYAAAUA" + \
"AAAAAtwGAAADAAcACwAPABMAACEjETMDIxEzASMRMxMjETMDIxEzAtyMjMA0NP7YNDRoNDTQjIwG" + \
"APoABgD6AAYA+gAGAPoABgAAAAUAAAAAAtwGAAADAAcACwAPABMAACEjETMBIxEzASMRMwEjETMB" + \
"IxEzAVw0NP7YNDQCqIyM/hiMjAEoNDQGAPoABgD6AAYA+gAGAPoABgAABQAAAAAC3AYAAAMABwAL" + \
"AA8AEwAAISMRMwEjETMBIxEzAyMRMwEjETMCdDQ0/hiMjAEoNDRojIwBkDQ0BgD6AAYA+gAGAPoA" + \
"BgD6AAYAAAAFAAAAAALcBgAAAwAHAAsADwATAAAhIxEzASMRMwMjETMBIxEzASMRMwIcNDT+gDQ0" + \
"aDQ0ASiMjAGAjIwGAPoABgD6AAYA+gAGAPoABgABAAUAAAAAAtwGAAADAAcACwAPABMAACEjETMB" + \
"IxEzASMRMwEjETMBIxEzAbSMjAEoNDT+GDQ0AYA0NP4YjIwGAPoABgD6AAYA+gAGAPoABgAABQAA" + \
"AAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMTIxEzEyMRMwEjETMCdDQ0/cA0NMCMjMCMjAEoNDQG" + \
"APoABgD6AAYA+gAGAPoABgAABQAAAAAC3AYAAAMABwALAA8AEwAAMyMRMxMjETMDIxEzASMRMwMj" + \
"ETOcNDRoNDTQNDQCqIyMwIyMBgD6AAYA+gAGAPoABgD6AAYAAAUAAAAAAtwGAAADAAcACwAPABMA" + \
"ACEjETMTIxEzASMRMxMjETMDIxEzAnSMjGg0NP4YNDRoNDTQjIwGAPoABgD6AAYA+gAGAPoABgAB" + \
"AAUAAAAAAtwGAAADAAcACwAPABMAACEjETMBIxEzASMRMxMjETMBIxEzAVw0NP7YNDQCQIyMaDQ0" + \
"/hiMjAYA+gAGAPoABgD6AAYA+gAGAAAABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMDIxEz" + \
"ASMRMwEjETMC3DQ0/cA0NGg0NAEojIwBGIyMBgD6AAYA+gAGAPoABgD6AAYAAAAFAAAAAALcBgAA" + \
"AwAHAAsADwATAAAhIxEzASMRMwMjETMTIxEzAyMRMwLcjIz+6DQ00DQ0aDQ00IyMBgD6AAYA+gAG" + \
"APoABgD6AAYAAwAFAAAAAALcBgAAAwAHAAsADwATAAAhIxEzASMRMwEjETMBIxEzAyMRMwFcNDT+" + \
"2DQ0AqiMjP7oNDTQjIwGAPoABgD6AAYA+gAGAPoABgAQAAUAAAAAAtwGAAADAAcACwAPABMAACEj" + \
"ETMBIxEzASMRMwMjETMTIxEzAtw0NP2wjIwBkDQ00IyMaDQ0BgD6AAYA+gAGAPoABgD6AAYAAAUA" + \
"AAAAAtwGAAADAAcACwAPABMAACEjETMBIxEzAyMRMwEjETMBIxEzAcQ0NP7YNDRoNDQCqIyM/oCM" + \
"jAYA+gAGAPoABgD6AAYA+gAGAMQABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMDIxEzASMR" + \
"MwEjETMCHDQ0/tg0NGiMjAJQNDT+2IyMBgD6AAYA+gAGAPoABgD6AAYAAAAFAAAAAALcBgAAAwAH" + \
"AAsADwATAAAhIxEzASMRMxMjETMBIxEzASMRMwIcNDT+GDQ0wIyMAeg0NP7YjIwGAPoABgD6AAYA" + \
"+gAGAPoABgAAAAUAAAAAAtwGAAADAAcACwAPABMAADMjETMTIxEzAyMRMwEjETMBIxEznDQ0aDQ0" + \
"0DQ0AZCMjAEYjIwGAPoABgD6AAYA+gAGAPoABgAAAAUAAAAAAtwGAAADAAcACwAPABMAACEjETMT" + \
"IxEzASMRMxMjETMDIxEzAhyMjMA0NP4YNDRoNDTQjIwGAPoABgD6AAYA+gAGAPoABgAAAAUAAAAA" + \
"AtwGAAADAAcACwAPABMAACEjETMBIxEzASMRMxMjETMBIxEzAVw0NP7YNDQB6IyMwDQ0/hiMjAYA" + \
"+gAGAPoABgD6AAYA+gAGAAAABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMDIxEzASMRMxMj" + \
"ETMC3DQ0/cA0NGg0NAEojIzAjIwGAPoABgD6AAYA+gAGAPoABgAABQAAAAAC3AYAAAMABwALAA8A" + \
"EwAAISMRMwEjETMTIxEzEyMRMxMjETMC3IyM/bCMjMA0NGg0NGg0NAYA+gAGAPoABgD6AAYA+gAG" + \
"AAUABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMTIxEzEyMRMwEjETMC3IyM/nCMjGg0NGg0" + \
"NP4YNDQGAPoABgD6AAYA+gAGAPoABgAABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMBIxEz" + \
"EyMRMwMjETMBpIyM/uiMjAGANDTQNDRoNDQGAPoABgD6AAYA+gAGAPoABgAABQAAAAAC3AYAAAMA" + \
"BwALAA8AEwAAMyMRMwEjETMDIxEzASMRMwEjETP0NDQB6IyMwDQ0/hg0NAGAjIwGAPoABgD6AAYA" + \
"+gAGAPoABgAABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwEjETMTIxEzASMRMxMjETMCDIyM/oCM" + \
"jMA0NAEoNDRoNDQGAPoABgD6AAYA+gAGAPoABgAABQAAAAAC3AYAAAMABwALAA8AEwAAISMRMwMj" + \
"ETMDIxEzASMRMwEjETMC3DQ00IyMwIyMASg0NP3ANDQGAPoABgD6AAYA+gAGAPoABgAABQAAAAAC" + \
"3AYAAAMABwALAA8AEwAAMyMRMwEjETMBIxEzASMRMwEjETP0NDQB6IyM/oA0NP7YNDQB6IyMBgD6" + \
"AAYA+gAGAPoABgD6AAYAAAAFAAAAAALcBgAAAwAHAAsADwATAAAhIxEzASMRMwEjETMBIxEzAyMR" + \
"MwJ0jIz+GIyMAlA0NP7YNDRoNDQGAPoABgD6AAYA+gAGAPoABgAAAAUAAAAAAtwGAAADAAcACwAP" + \
"ABMAACEjETMTIxEzASMRMwEjETMBIxEzAbQ0NMCMjP7YjIwBkDQ0/Vg0NAYA+gAGAPoABgD6AAYA" + \
"+gAGAAAABQAAAAAC3AYAAAMABwALAA8AEwAAMyMRMxMjETMTIxEzEyMRMwEjETP0NDTANDTANDRo" + \
"NDT9WDQ0BgD6AAYA+gAGAPoABgD6AAYAAAUAAAAAAtwGAAADAAcACwAPABMAADMjETMTIxEzASMR" + \
"MwMjETMBIxEz9DQ0wDQ0ASg0NMA0NP4YNDQGAPoABgD6AAYA+gAGAPoABgAGAAUAAAAAAtwGAAAD" + \
"AAcACwAPABMAADMjETMBIxEzAyMRMwEjETMBIxEz9DQ0ASg0NMA0NAGANDT9WDQ0BgD6AAYA+gAG" + \
"APoABgD6AAYAAAUAAAAAAtwGAAADAAcACwAPABMAACEjETMDIxEzASMRMxMjETMBIxEzAVw0NMA0" + \
"NAGANDTANDT9WDQ0BgD6AAYA+gAGAPoABgD6AAYAAAAAAQAAAAAAADoO7dpfDzz1AAAIAAAAAAAA" + \
"AAAAAAAAALaKklYAAAAAAtwGBAAAAAAAAAAAAAAAAAABAAAGBAAAAAADGgAAADQC3AAAAAAAAAAA" + \
"AAAAAAAAAAAAAQMQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" + \
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAY" + \
"AD8AZgCNALQA2wEDASsBUgF5AaEByAHvAhcCPwJnAo8CtgLcAwMDKwNTA3oDogPJA/EEGQRBBGgE" + \
"jwS3BN4FBQUsBVMFegWhBcgF8AYYBkAGZgaNBrQG2wABAAAALwAUAAUAAAAAAAEAAAAAAAAAAAAA" + \
"AAAAAAABAAAAEADGAAEAAAAAAAAACQEoAAEAAAAAAAEAAwEPAAEAAAAAAAIABwD6AAEAAAAAAAMA" + \
"AwC3AAEAAAAAAAQAAwCOAAEAAAAAAAUADABqAAEAAAAAAAYAAwBXAAEAAAAAAAcACQAAAAMAAQQJ" + \
"AAAAbgExAAMAAQQJAAEAFgESAAMAAQQJAAIADgEBAAMAAQQJAAMAQAC6AAMAAQQJAAQAJgCRAAMA" + \
"AQQJAAUAGAB2AAMAAQQJAAYAEABaAAMAAQQJAAcATgAJVHJhZGVtYXJrAEYAcgBlAGUAIAAzACAA" + \
"bwBmACAAOQCZACAAVAByAGEAZABlAG0AYQByAGsAIABvAGYAIABNAGEAdAB0AGgAZQB3ACAAVwBl" + \
"AGwAYwBoTmV3AEYAcgBlAGUAMwBvAGYAOVZlcnNpb24gMS4wMABWAGUAcgBzAGkAbwBuACAAMQAu" + \
"ADAAMU5ldwBGAHIAZQBlACAAMwAgAG8AZgAgADkAIABSAGUAZwB1AGwAYQByTmV3AEYAcgBlAGUA" + \
"IAAzACAAbwBmACAAOQAgAFIAZQBnAHUAbABhAHIAOgBWAGUAcgBzAGkAbwBuACAAMQAuADAAMVJl" + \
"Z3VsYXIAUgBlAGcAdQBsAGEAck5ldwBGAHIAZQBlACAAMwAgAG8AZgAgADlDb3B5cmlnaHQAQwBv" + \
"AHAAeQByAGkAZwBoAHQAIACpACAAMQA5ADkANwAgAGIAeQAgAE0AYQB0AHQAaABlAHcAIABXAGUA" + \
"bABjAGgALgAgAEEAbABsACAAUgBpAGcAaAB0AHMAIABSAGUAcwBlAHIAdgBlAGQALgAAAAAAAAAA" + \
"AAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

if __name__ == '__main__':
   main()
